### ISSUE TITLE
How minimal are you keeping your bindings? 

### ISSUE THREAD

**Issue by dgryski** [codahale/geoip#1]
Because of a number of outstanding issues with abh/geoip I'm planning on using your library as a base for some patches I need for a project.  Specifically, moving away from the non-thread-safe APIs and adding the time zone lookup.  To fully switch to your library I'm also adding support for the GetName function used by the ISP and netspeed data files and region name lookup. 

Are you planning on keeping your package small or would you be interested in these patches?

**Comment by codahale** [comment]
I’d be happy to accept patches for additional functionality.
